# Generated by Django 3.1.6 on 2021-03-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20210205_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='icon_color',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='type',
            field=models.CharField(choices=[('pub', 'Public Group'), ('pri', 'Private Group')], max_length=3),
        ),
    ]
