# Generated by Django 3.1.6 on 2021-03-12 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20210312_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='icon_color',
            field=models.CharField(default='#9E579D', max_length=7),
        ),
    ]
