# Generated by Django 3.1.6 on 2021-03-18 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_auto_20210318_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tasklist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task.tasklist'),
        ),
    ]
