# Generated by Django 3.1.6 on 2021-03-31 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_subtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task.group'),
        ),
    ]
