# Generated by Django 3.1.6 on 2021-04-01 17:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0012_remove_group_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='users1',
        ),
        migrations.AddField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
