# Generated by Django 3.1.6 on 2021-04-01 17:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0013_auto_20210402_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='users1',
            field=models.ManyToManyField(related_name='users1', through='task.Membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
