# Generated by Django 3.1.6 on 2021-04-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0017_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='completed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('on', 'On progress'), ('new', 'Created'), ('ready', 'Completed')], default='new', max_length=7),
        ),
    ]
