# Generated by Django 3.1.6 on 2021-04-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0018_auto_20210405_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='status',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('on', 'On progress'), ('new', 'Created'), ('ready', 'Completed')], default='new', max_length=7),
        ),
    ]
