# Generated by Django 3.1.6 on 2021-04-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0020_auto_20210415_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='readiness',
            field=models.IntegerField(default=0),
        ),
    ]
