# Generated by Django 3.1.5 on 2021-01-26 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_editor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
